image: Ubuntu  

stack: jdk 11  

branches:
  only:
    - main 

build: off  

install:
  # запускаем SUT 
  - java -jar ./artifacts/app-order.jar &
  - chmod +x gradlew

  build_script:
  - ./gradlew test --info -Dselenide.headless=true
